### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by FulltronService** [cdgco/VestaWebInterface#71]
When trying to install the script, I always get "Connection failure, check the configuration file" but I see it and it's all good. Help me, I had to uninstall it.

**Comment by cdgco** [comment]
Hello, I am sorry for the issue. Is your domain pop.vps.co.ve?

**Comment by FulltronService** [comment]
Yes, It is the domain domain of one of the backup servers.

**Comment by cdgco** [comment]
Could you please attempt to reinstall Vesta Web Interface, then edit your
.htaccess file and change the PHP Flags option to "On" and I will attempt
to diagnose the problem.


On Oct 21, 2018 at 2:31 PM, <FulltronService <notifications@github.com>>
wrote:

Yes, It is the domain domain of one of the backup servers.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cdgco/VestaWebInterface/issues/71#issuecomment-431702202>,
or mute the thread

**Comment by cdgco** [comment]
Try to log in and see if there are any new error messages.


On Oct 21, 2018 at 4:49 PM, <FulltronService <notifications@github.com>>
wrote:

Notice: Undefined index: username in /home/admin/web/
example.com/public_html/includes/includes.php on line 67

Notice: Undefined index: loggedin in /home/admin/web/
example.com/public_html/includes/includes.php on line 68

Warning: array_values() expects parameter 1 to be array, null given in
/home/admin/web/example.com/public_html/login.php on line 41

That is the error that shows me

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cdgco/VestaWebInterface/issues/71#issuecomment-431713132>,
or mute the thread

**Comment by FulltronService** [comment]
I already did it and I see exactly the same error, check by setting the value of that line to 1 but it gives me exactly the same error.

**Comment by cdgco** [comment]
All of those messages are expected and go away once you login, which makes
me believe there is another error. Those errors do not need to be changed
or fixed, they are only informational.


On Oct 22, 2018 at 12:43 PM, <FulltronService <notifications@github.com>>
wrote:

I already did it and I see exactly the same error, check by setting the
value of that line to 1 but it gives me exactly the same error.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cdgco/VestaWebInterface/issues/71#issuecomment-431927699>,
or mute the thread

**Comment by FulltronService** [comment]
Correct, I also say the same but the strange thing is that when I start session it tells me that the data is incorrect and that I am very sure of the data I put as I use it every day.

**Comment by cdgco** [comment]
Since it seems that PHP is unable to connect to your specified
MySQL database, I would start by checking that your port is correct and
there are no spelling errors, as well as ensuring that your MySQL port is
not blocked by either CentOS or VestaCP.
Alternatively, you can enable local configuration mode by changing the
value $configstyle to "2" in the includes/includes.php file and uploading a
manual configuration to the /tmp folder using the attached template.

**Comment by FulltronService** [comment]
Hello friend, with that additional configuration remains exactly the same even with the config.json installed in the folder ./tmp

Check the port that is 3306 and it's open, I do not understand why it's still not loading.

**Comment by cdgco** [comment]
I'm sorry, I misunderstood the problem. It seems you are able to connect to
MySQL but cannot connect to the VestaCP API. See if you can connect to
YOUR-DOMAIN.com:8083/api . You should get a blank white page. If that works
and there is still no explanation, use SSH on your VestaCP server and the
'v-generate-api-key' command, switch your authentication method to 'api'
and see if you can connect.


On Oct 23, 2018 at 6:36 AM, <FulltronService <notifications@github.com>>
wrote:

Hello friend, with that additional configuration remains exactly the same
even with the config.json installed in the folder ./tmp

Check the port that is 3306 and it's open, I do not understand why it's
still not loading.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cdgco/VestaWebInterface/issues/71#issuecomment-432234971>,
or mute the thread

**Comment by FulltronService** [comment]
But in what part do I place that API? What line exactly?

**Comment by cdgco** [comment]
Just check that it is accessible from your SSH terminal and/or browser. The
credentials will go in either you MySQL config or config.json for the
vesta-method value.


On Oct 23, 2018 at 8:21 AM, <FulltronService <notifications@github.com>>
wrote:

But in what part do I place that API? What line exactly?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cdgco/VestaWebInterface/issues/71#issuecomment-432279522>,
or mute the thread

**Comment by FulltronService** [comment]
The problem still persists, changing Vesta method to API. Enter the API in the empty field and stay the same.

**Comment by FulltronService** [comment]
The problem still persists, changing Vesta method to API. Enter the API in the empty field and stay the same.

**Comment by FulltronService** [comment]
The problem still persists, changing Vesta method to API. Enter the API in the empty field and stay the same.

**Comment by Holbroom** [comment]
Hi, I am having the same problem, I have been trying to get this working all day, I have done all the checks and still I get Failed to connect to server.Please check config, are there any logs i can check to see where the connection is failing?

**Comment by cdgco** [comment]
@Holbroom Are you able to successfully login once changing that line? The purpose of that line is to make a basic call to the Vesta server and produce an error if it cannot, whereas this edit would prevent the call from failing if it can't connect.

**Comment by cdgco** [comment]
One possible log you could check, by the way, is the Vesta auth log (/usr/local/vesta/log/auth.log) it should show a new event for every page load and show any authentication / credential problems.

**Comment by Holbroom** [comment]
Hi,
Unfortunately not, the edit made no difference,but if you visit the page and view the source you'll see multiple errors, not sure what is wrong to be honest.
https://control.holbrookhosting.co.uk

I've done manual install 3 times, once on a subdomain and twice in a directory of the main domain, all times with the same issue, oddly, when i run the auto install i get:

Error: VWI can only be installed on Debian, Ubuntu, CentOS, or RHEL. Exiting ...\n

But I am running centos.
# cat /etc/centos-release
CentOS release 6.10 (Final)

**Comment by cdgco** [comment]
@Holbroom Try running each of these commands then paste the output:
* `source /etc/os-release | echo $NAME`
* `lsb_release -si`
* `source /etc/lsb-release | echo $DISTRIB_ID`

These are the commands the installer uses to determine your OS but there must be something misspelled or missing in the installer.

**Comment by cdgco** [comment]
That is odd though, especially considering almost half of my users use CentOS and I've never heard of this issue before.

**Comment by cdgco** [comment]
Also, try creating a file called `test.php` with the following code in the /home/user/web/control.holbrookhosting.co.uk/public_html/ folder so I can see the raw output of the curl command and server connection.

```
<?php

session_start(); $configlocation = "includes/"; require('includes/includes.php');

$postvars = array(
   array('user' => $vst_username,'password' => $vst_password,'cmd' => 'v-list-sys-info','arg1' => 'json'),
   array('user' => $vst_username,'password' => $vst_password,'cmd' => 'v-list-sys-config','arg1' => 'json'));

$curl0 = curl_init();$curl1 = curl_init(); $curlstart = 0; 

while($curlstart <= 1) {
    curl_setopt(${'curl' . $curlstart}, CURLOPT_URL, $vst_url);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_RETURNTRANSFER,true);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_POST, true);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_POSTFIELDS, http_build_query($postvars[$curlstart]));
    $curlstart++;
} 
print_r(curl_exec($curl0)); print_r(curl_exec($curl1));
```

**Comment by FulltronService** [comment]
Hello, I get the same thing as him, exactly the same. And when I create and access the test.php I get the following.

Notice: Undefined index: username in /home/admin/web/pop.vps.co.ve/public_html/includes/includes.php on line 67

Notice: Undefined index: loggedin in /home/admin/web/pop.vps.co.ve/public_html/includes/includes.php on line 68

**Comment by cdgco** [comment]
Okay, that looks exactly as it should, try this now, and make sure there is no sensitive content / don't post it. Just make sure that it is actually outputting all of the correct data, and is not missing anything.

```
<?php

require("includes/config.php"); 

$result = mysqli_query(mysqli_connect($mysql_server,$mysql_uname,$mysql_pw,$mysql_db),"SELECT VARIABLE,VALUE FROM " . $mysql_table . "config");

while ($row = mysqli_fetch_assoc($result)) { echo $row["VARIABLE"] . " "  . $row["VALUE"] . "\n <br>"; }
mysqli_close($con);
```

**Comment by FulltronService** [comment]
TIMEZONE America/La_Paz 
SITE_NAME Backup Server 
THEME orange 
LANGUAGE es_US.utf8 
DEFAULT_TO_ADMIN true 
VESTA_HOST_ADDRESS https://pop.vps.co.ve 
VESTA_SSL_ENABLED true 
VESTA_PORT 8083 
VESTA_METHOD credentials 
VESTA_API_KEY 
VESTA_ADMIN_UNAME admin 
VESTA_ADMIN_PW PassWord 
KEY1 VmeE4TYY 
KEY2 kii7f7kt 
WARNINGS_ENABLED admin 
ICON admin-logo.png 
LOGO admin-text.png 
FAVICON favicon.ico 
WEB_ENABLED true 
DNS_ENABLED true 
MAIL_ENABLED true 
DB_ENABLED true 
ADMIN_ENABLED true 
PROFILE_ENABLED true 
CRON_ENABLED true 
BACKUPS_ENABLED true 
REGISTRATIONS_ENABLED false 
SOFTACULOUS_URL true 
OLD_CP_LINK true 
PHPMAIL_ENABLED false 
MAIL_FROM hello@https://pop.vps.co.ve 
MAIL_NAME Backup Server 
SMTP_ENABLED false 
SMTP_PORT 587 
SMTP_HOST 
SMTP_AUTH true 
SMTP_UNAME 
SMTP_PW 
SMTP_ENC tls 
FTP_URL 
WEBMAIL_URL 
PHPMYADMIN_URL 
PHPPGADMIN_URL 
SUPPORT_URL https://fulltron.net 
PLUGINS 
GOOGLE_ANALYTICS_ID 
INTERAKT_APP_ID 
INTERAKT_API_KEY 
CLOUDFLARE_API_KEY 
CLOUDFLARE_EMAIL 

Notice: Undefined variable: con in /home/admin/web/pop.vps.co.ve/public_html/test.php on line 8

Warning: mysqli_close() expects parameter 1 to be mysqli, null given in /home/admin/web/pop.vps.co.ve/public_html/test.php on line 8

**Comment by cdgco** [comment]
@FulltronService I believe the problem is with your VESTA_HOST_ADDRESS, it should be just the hostname or ip address, whereas you put a full url. Try replacing `https://pop.vps.co.ve` with `pop.vps.co.ve` in your MySQL database.

**Comment by FulltronService** [comment]
Ready, problem solved :)

Although showing errors, I still see some warnings, is it normal?

**Comment by cdgco** [comment]
@FulltronService Yes, those are just notices checking to see if you are logged in and are expected. You can turn off `php_flag display_errors` in .htaccess and those will go away.

I will also add some code to the installer to prevent this error from happening in the future.

**Comment by FulltronService** [comment]
Excellent friend, I am very grateful to you for the help you gave me. I would donate if it was not from Venezuela :(

Although we are hands.

**Comment by cdgco** [comment]
@FulltronService I'm glad I could help :)

**Comment by FulltronService** [comment]
I have other problem. When I want to configure a web I get:

Error Updating Web Domain
(E: 0.0.0.0.0.0.4.OK.0)

Please try again or contact support.

It is normal? You are not saving the web configuration.

**Comment by cdgco** [comment]
Is this when you are editing or creating a domain?

**Comment by Holbroom** [comment]
Good morning,
I have done done the same as above but it's still not working....

[root@holbrookhosting includes]# source /etc/os-release | echo $NAME
-bash: /etc/os-release: No such file or directory

[root@holbrookhosting includes]# lsb_release -si
CentOS

[root@holbrookhosting includes]# source /etc/lsb-release | echo $DISTRIB_ID
-Blank Output-

https://control.holbrookhosting.co.uk/test.php

and also the output of the other code.
ADMIN_ENABLED true 
BACKUPS_ENABLED true 
CLOUDFLARE_API_KEY 
CLOUDFLARE_EMAIL 
CRON_ENABLED true 
DB_ENABLED true 
DEFAULT_TO_ADMIN true 
DNS_ENABLED true 
FAVICON favicon.ico 
FTP_URL 
GOOGLE_ANALYTICS_ID 
ICON admin-logo.png 
INTERAKT_API_KEY 
INTERAKT_APP_ID 
KEY1 JbWm3BPP 
KEY2 PWkDVBjN 
LANGUAGE en_US.utf8 
LOGO admin-text.png 
MAIL_ENABLED true 
MAIL_FROM hello@holbrookhosting.co.uk 
MAIL_NAME Holbrook Hosting 
OLD_CP_LINK false 
PHPMAIL_ENABLED false 
PHPMYADMIN_URL 
PHPPGADMIN_URL 
PLUGINS 
PROFILE_ENABLED true 
REGISTRATIONS_ENABLED false 
SITE_NAME Holbrook Hosting 
SMTP_AUTH true 
SMTP_ENABLED false 
SMTP_ENC tls 
SMTP_HOST 
SMTP_PORT 587 
SMTP_PW 
SMTP_UNAME 
SOFTACULOUS_URL false 
SUPPORT_URL 
THEME default 
TIMEZONE Europe/London 
VESTA_ADMIN_PW -HIDDEN-
VESTA_ADMIN_UNAME admin
VESTA_API_KEY 
VESTA_HOST_ADDRESS 176.9.155.162 
VESTA_METHOD credentials 
VESTA_PORT 8083 
VESTA_SSL_ENABLED true 
WARNINGS_ENABLED admin 
WEBMAIL_URL 
WEB_ENABLED true 

Notice: Undefined variable: con in /home/admin/web/control.holbrookhosting.co.uk/public_html/test2.php on line 8

Warning: mysqli_close() expects parameter 1 to be mysqli, null given in /home/admin/web/control.holbrookhosting.co.uk/public_html/test2.php on line 8

**Comment by cdgco** [comment]
Also, it's odd that `/etc/os-release` is missing, because I believe that is supposed to work on a Linux releases, but I will try to fix the installer, and I will add `/etc/centos-release` as a backup check.

**Comment by Holbroom** [comment]
I've changed VESTA_HOST_ADDRESS from the IP Address to holbrookhosting.co.uk and it's still not working, this is very frustrating, I would love to get this working.

**Comment by cdgco** [comment]
@Holbroom could you paste the output of the first bit of test.php code I posted?

**Comment by cdgco** [comment]
Try changing it to this code and seeing if it changes.

```
<?php

session_start(); $configlocation = "includes/"; require('includes/includes.php');

$postvars = array(
   array('user' => $vst_username,'password' => $vst_password,'cmd' => 'v-list-sys-info','arg1' => 'json'),
   array('user' => $vst_username,'password' => $vst_password,'cmd' => 'v-list-sys-config','arg1' => 'json'));

$curl0 = curl_init();$curl1 = curl_init(); $curlstart = 0; 

while($curlstart <= 1) {
curl_setopt(${'curl' . $curlstart}, CURLOPT_FOLLOWLOCATION, true),
    curl_setopt(${'curl' . $curlstart}, CURLOPT_URL, $vst_url);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_RETURNTRANSFER,true);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt(${'curl' . $curlstart}, CURLOPT_POST, true);
    curl_setopt(${'curl' . $curlstart}, 
CURLOPT_POSTFIELDS, http_build_query($postvars[$curlstart]));
    $curlstart++;
} 
print_r(curl_exec($curl0)); print_r(curl_exec($curl1));

```

**Comment by Holbroom** [comment]
I've updated the test.php file, has anything changed?

**Comment by FulltronService** [comment]
> Is this when you are editing or creating a domain?

Exactly, I always get that error

**Comment by FulltronService** [comment]
> I've updated the test.php file, has anything changed?

Why do not you try to reinstall that from 0 and then purge the database you're using for the panel?

Maybe it's some general configuration issue. Then, make sure that the HOST is as example.com and not as https://example.com/

**Comment by Holbroom** [comment]
> > I've updated the test.php file, has anything changed?
> 
> Why do not you try to reinstall that from 0 and then purge the database you're using for the panel?
> 
> Maybe it's some general configuration issue. Then, make sure that the HOST is as example.com and not as https://example.com/

I've tried to install 4 times now already, each time i get the same errors messages, I have tried with IP and example.com domain, both give same error, my Cenots is 64bit, could that have any impact? the Auto install script doesn't work for me also, it says i am not using Centos when I am.

**Comment by FulltronService** [comment]
> I've tried to install 4 times now already, each time i get the same errors messages, I have tried with IP and example.com domain, both give same error, my Cenots is 64bit, could that have any impact? the Auto install script doesn't work for me also, it says i am not using Centos when I am.

It's quite weird that's the truth because I also use 64bit Cents and it did not give me any problem in the installation except for the configuration file. Did you install the Development Tools?

**Comment by FulltronService** [comment]
> I add that my version of Centos is the 7, in the registry of errors of the domain of VestaCP sometimes it leaves to you that the problem can be for the PHP-FCGI as it happened to me and already that is external to the support of the panel that you are installing . To enter I think you know, in any case enter in this way to that record:
> 
> Control Panel (Original VestaCP Panel) > Web > View Logs (In your domain) > ErrorLog

If the problem is with your VestaCP Panel, there will be the reason why (If it is due to waiting time limit, if it is because there is a wrong function or if it is because the number of simultaneous requests exceeds the limit)

**Comment by FulltronService** [comment]
@cdgco Do not you think the same?

**Comment by Holbroom** [comment]
Can you give me some suggestions to fix the issue?

**Comment by FulltronService** [comment]
> Can you give me some suggestions to fix the issue?

I'm waiting to see what it says @cdgco

**Comment by Holbroom** [comment]
Cheers, I really appreciate all the help, I'd love to get this working.

**Comment by FulltronService** [comment]
@cdgco I just found another problem and that is a problem. When I add a mail account I get (Error 500)

if I start to see the error log, I get this: `mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected ';', expecting ',' or ')' in /home/admin/web/panel.fulltron.net/public_html/create/mailaccount.php on line 125, referer: https://panel.fulltron.net/add/mailaccount.php?domain=tuservinet.com`

The code segment that is in that line is the following:

`if($webmailurl != ''){ $webmailurlx0 = "Webmail URL: <a href='" . $webmailurl . "'>" . $webmailurl . "</a>"; $webmailurlx1 = "Webmail URL: " . $webmailurl; } 
    else { $webmailurlx0 = ''; $webmailurlx1 = ''; }
    addslashes(
    $mail = new PHPMailer;
    $mail->setFrom($mailfrom, $mailname);
    $mail->addAddress($_POST['v_sendemail']);
    $mail->Subject = 'Email Credentials';
    $mail->Body = 'Username: ' . $_POST['v_account'] . '@' . $_POST['v_domain'] . '<br>IMAP Hostname: ' . addslashes(VESTA_HOST_ADDRESS) . '<br>IMAP Port: 143<br>IMAP Security: STARTTLS<br>IMAP Auth Method: Normal Password<br>SMTP Hostname: ' . addslashes(VESTA_HOST_ADDRESS) . '<br>SMTP Port: 587<br>SMTP Security: STARTTLS<br>SMTP Auth Method: Normal Password<br>Password: ' . $_POST['password'] . '<br>' . addslashes($webmailurlx1); 
    $mail->AltBody = 'Username: ' . $_POST['v_account'] . '@' . $_POST['v_domain'] . '\nIMAP Hostname: ' . addslashes(VESTA_HOST_ADDRESS) . '\nIMAP Port: 143\nIMAP Security: STARTTLS\nIMAP Auth Method: Normal Password\nSMTP Hostname: ' . addslashes(VESTA_HOST_ADDRESS) . '\nSMTP Port: 587\nSMTP Security: STARTTLS\nSMTP Auth Method: Normal Password\nPassword: ' . $_POST['password'] . '\n' . addslashes($webmailurlx0);
`

And especially line 125 is this:

`$mail = new PHPMailer;` 

He says he waits "," or ")" instead of ";" and that if I do not understand it since I change the values by "," or ")" and still throw the same message exactly the same.

**Comment by cdgco** [comment]
@Holbroom Your OS version has nothing to do with the errors, the only problem with the installation was an error in accurately detecting your OS. 

@FulltronService I need to know exactly which page this was because each page has a different error code meaning different things. Does the page end in /edit/domain.php or /add/domain.php?

I have school right now, so it will be a while before I can offer you any support.

**Comment by FulltronService** [comment]
Is this `https://panel.fulltron.net/create/mailaccount.php`. And okay, I'll be waiting.

**Comment by cdgco** [comment]
That error was fixed in commit 004a24f and will be released in v0.5.4

**Comment by cdgco** [comment]
@FulltronService the error you received when updating the domain was an error code 4 when updating your domain's SSL certificate. Error 4 means "Object already exists". Presumably you already had an ssl certificate and uploaded the same one. For more info, view your Vesta error log in /usr/local/vesta/log/error.log

**Comment by cdgco** [comment]
@Holbroom, while adding that line did fix the redirection error, cURL is still unable to either connect to your VestaCP API, or authenticate. I will try to write some new test code later to hopefully determine the issue.

**Comment by Holbroom** [comment]
Thank you, I really appreciate the help.

**Comment by Holbroom** [comment]
I don't understand how I can use VestaCP API in PHP for creating accounts etc, but this is still failing, it's connecting to the mysql database but doesn't appear to be talking to VestaCP API

**Comment by cdgco** [comment]
@Holbroom, I don't understand either, all the data looks correct, but the test.php should be outputting data, whereas it is blank but also not giving and connection errors. It could be a problem with your php or cURL, but I am not sure.

**Comment by Holbroom** [comment]
My cURL version is very outdated.

Version: 7.19.7 Nov 4 2009 

I'm going to update this and see if that helps, clutching at straws now.

**Comment by Holbroom** [comment]
I have updated everything but still hasn't made any difference.

Do you know why I get the following message why I try to do an Automatic Install?
Error: VWI can only be installed on Debian, Ubuntu, CentOS, or RHEL. Exiting ...\n

Also, is there anything more we can try, maybe a script to test the cURL connection to the API?
Proving PHPInfo if there is anything to check? https://control.holbrookhosting.co.uk/phpinfo.php

**Comment by cdgco** [comment]
@Holbroom, As I said, the only problem with the automatic installer is that the section which I built to detect your OS was working wrong and I need to add 1 more line. 

I plan on writing a script to debug the curl connection, but I have had very little free time lately.

I will take a look at your PHPInfo, but I doubt it will give me much more insight than I currently have. 

You are running the same operating system and kernel as other users as well as the same PHP, Apache and HTTP versions.

**Comment by cdgco** [comment]
@Holbroom if you really want to use the automated installer, here is a script to force it:
```
#!/bin/bash
	if [ ! -z "$(ls -A ./)" ]; then
		printf "Error: Directory not empty.\nVWI must be installed in clean directory. Exiting ...\n"
		exit 1
	fi
	printf "Checking for required packages ...\n"
        if rpm -q wget &> /dev/null
	then
		echo "wget found"
	else
		echo "wget not found. Installing ..."
		yum -y install wget
	fi
	if rpm -q tar &> /dev/null
	then
		echo "tar found"
	else
		echo "tar not found. Installing ..."
		yum -y install tar
	fi
	if rpm -q git &> /dev/null
	then
		echo "git found"
	else
		echo "git not found. Installing ..."
		yum -y install git
	fi
	printf "\nInstalling Vesta Web Interface frontend ...\n"
	git clone --quiet https://github.com/cdgco/VestaWebInterface . > /dev/null
    git checkout --quiet 94b41e0 > /dev/null
	if [ -f README.md ] ; then
		rm README.md
	elif [ -f 'VWI Banner.png' ] ; then
		rm 'VWI Banner.png'
	fi
	chmod 777 includes
    chmod 777 tmp
    chmod 777 plugins/images/uploads
	printf "Installing Vesta Web Interface backend ...\n"
	sleep .5
	if [ -d /usr/local/vesta/softaculous/enduser/themes/default ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/default /usr/local/vesta/softaculous/enduser/themes/original-default -r
	elif [ -d /usr/local/vesta/softaculous/enduser/themes/simple ] ; then
		cp /usr/local/vesta/softaculous/enduser/themes/simple /usr/local/vesta/softaculous/enduser/themes/original-simple -r
	fi
	wget -q https://github.com/cdgco/VestaWebInterface/releases/download/v0.5.3-Beta/backend.tar.gz
	if [ -f backend.tar.gz ] ; then
		tar -xzf backend.tar.gz -C /usr/local/
		rm backend.tar.gz
	fi
	read -p "Enter the full web address of your installation: "
        echo "<?php \$vwipanel = '$REPLY'; ?>" > /usr/local/vesta/web/vwi/config.php
	printf "\nInstallation Complete! Please visit your website online to finish configuration.\n"
fi
```

**Comment by Holbroom** [comment]
Thank you, i'm going to wipe the site tonight and give the auto installer ago, to see if it makes any difference, I appreciate your time and effort to help get this working. cheers.
